name: Test Examples (datapackage)
on: [push, pull_request]

jobs:
  test_examples_datapackage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-test_examples
    - name: Install Python libs
      run: pip install --upgrade frictionless
    - name: Validate example
      run: frictionless validate examples/csv/datapackage.json
